# -*- coding: utf-8 -*-
"""activation_fun.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B1NvqJozCUEwT_Yc161iDI-i86TJy5RS
"""

import math

def sigmoid(x):
  return 1/(1+math.exp(-x))

sigmoid(1)

def tanh(x):
  return (math.exp(x) - math.exp(-x))/(math.exp(x) + math.exp(-x))

tanh(7)

def relu(x):
  return max(0,x)

relu(7)

relu(-7)

def leaky_relu(x):
  return max(0.1 * x, x)

leaky_relu(7)

leaky_relu(-7)

