# -*- coding: utf-8 -*-
"""TF_Input_Pipeline.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h_snMK-9Odu1SMpxoRl9dawAzOkpHaXt
"""

import tensorflow as tf

daily_sales = [21,42,-102, 45,76,54,-2,76]

tf_ds = tf.data.Dataset.from_tensor_slices(daily_sales)
tf_ds

for sales in tf_ds:
  print(sales.numpy())

for sales in tf_ds.take(5):
  print(sales.numpy())

tf_ds = tf_ds.filter(lambda x: x>0)
for sales in tf_ds:
  print(sales.numpy())

#suppose these are USD
tfd = tf_ds.map(lambda x : x*77)
for sales in tfd:
  print('Rs.', sales.numpy(),"/-")

tfd = tfd.shuffle(3)
for sales in tfd:
  print(sales.numpy())

#Batching
for sales in tfd.batch(3):
  print(sales.numpy())

#TF Pipeline
tfd = tf_ds.filter(lambda x: x>0).map(lambda y : y*77).shuffle(3).batch(2)
for i in tfd:
  print(i.numpy())

img_ds = tf.data.Dataset.list_files('')